id: IEF285E24
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-17T13:49:59.303761'
last_modified: '2022-06-17T13:49:59.303767'
parser: null
source_metadata:
  title: Rinchen Terdzö Series
  language: es
  description: 'Texts belonging to (and related to) the Rinchen Terdzö (rin chen gter
    mdzod) or Precious Treasury of Revelations, one of the five treasuries of Jamgön
    Kongtrul Lodrö Thayé (1813–1899). Note that the volume numbers below correspond
    to the Shechen Publications edition (2007–2008):'
  volume:
    f350E:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      base_file: f350E.txt
      order: 1
      parent: Volume 1
    f5557:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      base_file: f5557.txt
      order: 2
      parent: Volume 1
    f6777:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      base_file: f6777.txt
      order: 3
      parent: Volume 1
    fA520:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      base_file: fA520.txt
      order: 4
      parent: Volume 1
    fBACB:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      base_file: fBACB.txt
      order: 5
      parent: Volume 1
    f27A4:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      base_file: f27A4.txt
      order: 6
      parent: Volume 1
    f22F2:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      base_file: f22F2.txt
      order: 7
      parent: Volume 1
    f63F6:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      base_file: f63F6.txt
      order: 8
      parent: Volume 1
    f787F:
      title: The Lament of Rudra
      base_file: f787F.txt
      order: 9
      parent: Volume 5
    f31FE:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      base_file: f31FE.txt
      order: 10
      parent: Volume 5
    fD534:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      base_file: fD534.txt
      order: 11
      parent: Volume 5
    f5A25:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      base_file: f5A25.txt
      order: 12
      parent: Volume 5
    f01CE:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      base_file: f01CE.txt
      order: 13
      parent: Volume 5
    fE587:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      base_file: fE587.txt
      order: 14
      parent: Volume 5
    f4B9D:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      base_file: f4B9D.txt
      order: 15
      parent: Volume 5
    f4935:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      base_file: f4935.txt
      order: 16
      parent: Volume 5
    fAEA4:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      base_file: fAEA4.txt
      order: 17
      parent: Volume 6
    fB587:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      base_file: fB587.txt
      order: 18
      parent: Volume 10
    f654D:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      base_file: f654D.txt
      order: 19
      parent: Volume 10
    f84D4:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      base_file: f84D4.txt
      order: 20
      parent: Volume 10
    f489B:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      base_file: f489B.txt
      order: 21
      parent: Volume 10
    f6326:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      base_file: f6326.txt
      order: 22
      parent: Volume 10
    fD7E5:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      base_file: fD7E5.txt
      order: 23
      parent: Volume 10
    f3BCB:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      base_file: f3BCB.txt
      order: 24
      parent: Volume 10
    fF28F:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      base_file: fF28F.txt
      order: 25
      parent: Volume 11
    f0AD4:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      base_file: f0AD4.txt
      order: 26
      parent: Volume 11
    fEAC2:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      base_file: fEAC2.txt
      order: 27
      parent: Volume 11
    f86D7:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      base_file: f86D7.txt
      order: 28
      parent: Volume 11
    f6ABA:
      title: Ārya Mañjuśrī Tantra Garbha
      base_file: f6ABA.txt
      order: 29
      parent: Volume 16
    f15EE:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      base_file: f15EE.txt
      order: 30
      parent: Volume 16
    fFC65:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      base_file: fFC65.txt
      order: 31
      parent: Volume 21
    f9393:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      base_file: f9393.txt
      order: 32
      parent: Volume 22
    fDC2E:
      title: Prayer to the Lineage of the Supreme Hayagrīva Emanation from the Aural
        Transmission
      base_file: fDC2E.txt
      order: 33
      parent: Volume 26
    f4BB2:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      base_file: f4BB2.txt
      order: 34
      parent: Volume 31
    f4995:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      base_file: f4995.txt
      order: 35
      parent: Volume 32
    f61E4:
      title: Aspiration Prayer from Tārā Sādhana
      base_file: f61E4.txt
      order: 36
      parent: Volume 35
    fBA49:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart-Essence of the
        Vast Expanse'
      base_file: fBA49.txt
      order: 37
      parent: Volume 36
    f3224:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      base_file: f3224.txt
      order: 38
      parent: Volume 36
    f04F9:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      base_file: f04F9.txt
      order: 39
      parent: Volume 36
    fEBE2:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      base_file: fEBE2.txt
      order: 40
      parent: Volume 36
    fB24C:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      base_file: fB24C.txt
      order: 41
      parent: Volume 36
    fA1F8:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      base_file: fA1F8.txt
      order: 42
      parent: Volume 36
    f4191:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      base_file: f4191.txt
      order: 43
      parent: Volume 36
    fA2C3:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      base_file: fA2C3.txt
      order: 44
      parent: Volume 36
    fE377:
      title: The Twenty-Eight Commitments
      base_file: fE377.txt
      order: 45
      parent: Volume 41
    f20BF:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      base_file: f20BF.txt
      order: 46
      parent: Volume 41
    f7EDD:
      title: Verses of Confession 'Düsum Deshekma'
      base_file: f7EDD.txt
      order: 47
      parent: Volume 41
    fF1F1:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      base_file: fF1F1.txt
      order: 48
      parent: Volume 41
    f9757:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      base_file: f9757.txt
      order: 49
      parent: Volume 41
    f11F0:
      title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
        of Enlightened Body, Speech and Mind'
      base_file: f11F0.txt
      order: 50
      parent: Volume 41
    fF210:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      base_file: fF210.txt
      order: 51
      parent: Volume 41
    fB08F:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      base_file: fB08F.txt
      order: 52
      parent: Volume 42
    f44EC:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      base_file: f44EC.txt
      order: 53
      parent: Volume 42
    fCAFA:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      base_file: fCAFA.txt
      order: 54
      parent: Volume 42
    fE987:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      base_file: fE987.txt
      order: 55
      parent: Volume 43
    f290C:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      base_file: f290C.txt
      order: 56
      parent: Volume 43
    f4AA7:
      title: The Means for Accomplishment called the Blazing Wheel
      base_file: f4AA7.txt
      order: 57
      parent: Volume 45
    fABBC:
      title: 'The Beautiful Garland of Lotuses: A Prayer to the Lineage of the Rediscovered
        Treasure, Five-Deity Subjugative Hayagrīva'
      base_file: fABBC.txt
      order: 58
      parent: Volume 46
    fF2C4:
      title: Dispeller of All Samaya Corruptions and Pollutions
      base_file: fF2C4.txt
      order: 59
      parent: Volume 47
    f7764:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      base_file: f7764.txt
      order: 60
      parent: Volume 48
    f5758:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      base_file: f5758.txt
      order: 61
      parent: Volume 48
    f224C:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      base_file: f224C.txt
      order: 62
      parent: Volume 48
    fB64E:
      title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of
        Abhirati'
      base_file: fB64E.txt
      order: 63
      parent: Volume 48
    fEA6D:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      base_file: fEA6D.txt
      order: 64
      parent: Volume 49
    f6D03:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      base_file: f6D03.txt
      order: 65
      parent: Volume 49
    f98C4:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      base_file: f98C4.txt
      order: 66
      parent: Volume 49
    f3A64:
      title: Prayer for the Future of the Dharma
      base_file: f3A64.txt
      order: 67
      parent: Volume 52
    f6210:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      base_file: f6210.txt
      order: 68
      parent: Volume 52
    f305A:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      base_file: f305A.txt
      order: 69
      parent: Volume 52
    f5D92:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      base_file: f5D92.txt
      order: 70
      parent: Volume 52
    fBFA4:
      title: Prayer to the Lineage of the Great Chetsün’s Profound Essence of Vimala
      base_file: fBFA4.txt
      order: 71
      parent: Volume 56
    f06FF:
      title: The Aspiration of the Vajradhātu Maṇḍala
      base_file: f06FF.txt
      order: 72
      parent: Volume 60
    fA1A9:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      base_file: fA1A9.txt
      order: 73
      parent: Volume 60
    f082A:
      title: The Pointing-the-Staff Instruction
      base_file: f082A.txt
      order: 74
      parent: Volume 60
    f3969:
      title: Yeshe Tsogyal's Prayer
      base_file: f3969.txt
      order: 75
      parent: Volume 60
    f454E:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      base_file: f454E.txt
      order: 76
      parent: Volume 60
    fC47E:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      base_file: fC47E.txt
      order: 77
      parent: Volume 65
    fA8C9:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      base_file: fA8C9.txt
      order: 78
      parent: Volume 67
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
